server:
  port: 8085

spring:
  application:
    name: ANALYTICS-SERVICE

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/analytics_db
    username: ${ANALYTICS_DB_USERNAME}
    password: ${ANALYTICS_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

security:
  jwt:
    public-key-location: ${JWT_PUBLIC_KEY_LOCATION}
    issuer: ${JWT_ISSUER}
    audience: ${JWT_AUDIENCE}
