server:
  port: 8085

spring:
  application:
    name: ANALYTICS-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/analytics_db?createDatabaseIfNotExist=true
    username: ${ANALYTICS_DB_USERNAME}
    password: ${ANALYTICS_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: analytics-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.featureflag.analytics_service.event.FlagEvent

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

security:
  jwt:
    public-key-location: ${JWT_PUBLIC_KEY_LOCATION}
    issuer: ${JWT_ISSUER}
    audience: ${JWT_AUDIENCE}
