server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:mysql://host.docker.internal:3306/auth_db
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka

jwt:
  secret: ${AUTH_JWT_SECRET}
