server:
  port: 8081

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:mysql://mysql:3306/auth_db
    username: ${AUTH_DB_USERNAME}
    password: ${AUTH_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      show-components: never
      probes:
        enabled: true
      group:
        liveness:
          include: "livenessState"
        readiness:
          include: "readinessState,db"

security:
  jwt:
    private-key-location: ${AUTH_JWT_PRIVATE_KEY_LOCATION}
    public-key-location: ${JWT_PUBLIC_KEY_LOCATION}
    issuer: ${JWT_ISSUER}
    audience: ${JWT_AUDIENCE}
    access-token-ttl: ${JWT_ACCESS_TOKEN_TTL:15m}
    key-id: ${JWT_KEY_ID}
