server:
  port: 8082

spring:
  application:
    name: FLAG-SERVICE

  data:
    redis:
      host: redis
      port: 6379

  kafka:
    bootstrap-servers: kafka:29092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:mysql://mysql:3306/flag_db
    username: ${FLAG_DB_USERNAME}
    password: ${FLAG_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  instance:
    prefer-ip-address: true

  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      show-components: never
      probes:
        enabled: true
      group:
        liveness:
          include: "livenessState"
        readiness:
          include: "readinessState,db"

security:
  jwt:
    public-key-location: ${JWT_PUBLIC_KEY_LOCATION}
    issuer: ${JWT_ISSUER}
    audience: ${JWT_AUDIENCE}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
